### PR TITLE
fix: corrected spelling

### PR DESCRIPTION
**Pull request by TimeTravelPenguin**
Corrected spelling in the manual and in src comments

### CODE REVIEW

**Review by tingerrr — APPROVED** [review]

**Comment by tingerrr** [comment]
Thank you!

**Comment by TimeTravelPenguin** [comment]
> Thank you!

No problem. In one of the Typst repos, they mention using a tool called [Typos](https://github.com/crate-ci/typos). I just gave it a run once I spotted two of them on my own.

It is definitely worth adding to your CI and/or IDE's LSP.

**Comment by tingerrr** [comment]
I'm not sure if CI should fail because of a typo, I guess if @JamesxX wants to add it he can, I'm indifferent about it.

**Comment by TimeTravelPenguin** [comment]
To be fair, I only use it in my pre-commits. Doing anything like GH Actions is a pain unless it's a decently sized process, or if you prefer it.

**Pull request merged**
